# Generated by Django 2.1.1 on 2018-11-13 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20181111_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_delete_book', 'Delete book'),)},
        ),
    ]
