# Generated by Django 2.1.1 on 2018-11-14 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20181113_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'), ('can_borrow_book', 'User can borrow books'))},
        ),
    ]
